# Generated by Django 3.1.6 on 2021-10-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211018_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='author',
        ),
    ]
