# Generated by Django 3.2.7 on 2021-10-24 04:45

from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='displayName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('displayName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='username', serialize=False, to='users.displayname')),
                ('bio', models.CharField(default='egg dog', max_length=256)),
                ('url', models.URLField(default='https://github.com/2021fallCMPUT404/group-cmput404-project', unique=True)),
                ('profile_picture', models.ImageField(default='image/users/egg_dog.jpeg', upload_to=users.models.user_directory_path)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.myuuidmodel')),
            ],
        ),
        migrations.CreateModel(
            name='edit_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user_profile')),
            ],
        ),
    ]
