# Generated by Django 3.2.7 on 2021-10-25 00:05

import datetime
from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('displayName', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('bio', models.CharField(max_length=256)),
                ('url', models.URLField(default='https://github.com/2021fallCMPUT404/group-cmput404-project', unique=True)),
                ('profile_picture', models.ImageField(upload_to=users.models.user_directory_path)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
