# Generated by Django 3.1.6 on 2021-10-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='edit_hsitory',
            new_name='edit_history',
        ),
    ]
