# Generated by Django 3.2.7 on 2021-12-05 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(blank=True, max_length=60)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('first_name', models.CharField(blank=True, max_length=69)),
                ('last_name', models.CharField(blank=True, max_length=69)),
                ('profileImage', models.ImageField(blank=True, default='profile_picture/default_picture.png', upload_to='profile_picture')),
                ('github', models.CharField(blank=True, default='', max_length=100)),
                ('bio', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.user_profile')),
                ('object', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.user_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('follow', models.ManyToManyField(blank=True, null=True, to='users.FriendRequest')),
                ('like', models.ManyToManyField(blank=True, null=True, to='posts.Like')),
                ('post', models.ManyToManyField(blank=True, null=True, to='posts.Post')),
            ],
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='actor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='users.user_profile'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='object',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='object', to='users.user_profile'),
        ),
    ]
