# Generated by Django 3.2.7 on 2021-10-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='github',
            field=models.URLField(blank=True, default='https://github.com/2021fallCMPUT404/group-cmput404-project'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='profile_picture/default_picture.png', upload_to='profile_picture'),
        ),
    ]
