# Generated by Django 3.1.6 on 2021-12-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='actor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='object',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
