# Generated by Django 3.1.6 on 2021-10-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='created_date',
        ),
    ]
