# Generated by Django 3.2.7 on 2021-11-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='github',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
