# Generated by Django 3.1.6 on 2021-10-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_profile_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Followers',
            field=models.ManyToManyField(blank=True, to='users.User_Profile'),
        ),
    ]
