# Generated by Django 3.1.6 on 2021-10-29 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211029_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.user_profile')),
                ('object', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.user_profile')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='users.user_profile')),
                ('object', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='object', to='users.user_profile')),
            ],
        ),
    ]
