# Generated by Django 3.1.6 on 2021-12-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211205_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollows',
            name='actor',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userfollows',
            name='object',
            field=models.JSONField(),
        ),
    ]
