# Generated by Django 3.1.6 on 2021-10-23 16:54

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_inbox_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='displayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='bio',
            field=models.CharField(default='egg dog', max_length=256),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(default='image/users/egg_dog.jpeg', upload_to=users.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='url',
            field=models.URLField(default='https://github.com/2021fallCMPUT404/group-cmput404-project', unique=True),
        ),
        migrations.CreateModel(
            name='edit_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user_profile')),
            ],
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='displayName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.displayname'),
        ),
    ]
