# Generated by Django 3.1.6 on 2021-12-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=69),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=69),
        ),
    ]
