# Generated by Django 3.1.6 on 2021-10-27 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211027_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='actor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='users.user_profile'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='object',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='object', to='users.user_profile'),
        ),
    ]
