# Generated by Django 3.1.6 on 2021-12-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211205_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollows',
            name='actor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfollows',
            name='object',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
