# Generated by Django 3.1.6 on 2021-10-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendrequest_userfollows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user_posts',
        ),
    ]
