# Generated by Django 3.2.9 on 2021-12-06 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211201_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.user_profile')),
                ('sender', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.user_profile')),
            ],
        ),
    ]
