# Generated by Django 3.1.6 on 2021-10-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211027_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='Followers',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_user_profile_followers_+', to='users.User_Profile'),
        ),
    ]
