# Generated by Django 3.1.6 on 2021-10-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211023_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='displayName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='username', serialize=False, to='users.displayname'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.myuuidmodel'),
        ),
    ]
