# Generated by Django 3.1.6 on 2021-10-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211027_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='followers',
        ),
    ]
