# Generated by Django 3.1.6 on 2021-10-29 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userfollows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollows',
            name='actor_id',
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='object_id',
        ),
        migrations.AddField(
            model_name='userfollows',
            name='actor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.user_profile'),
        ),
        migrations.AddField(
            model_name='userfollows',
            name='object',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.user_profile'),
        ),
    ]
