# Generated by Django 3.1.6 on 2021-12-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('team_id', models.IntegerField(null=True)),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
