# Generated by Django 3.1.6 on 2021-10-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_on',
        ),
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.TextField(default='text/plain', editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='New Post!'),
        ),
    ]
