# Generated by Django 3.1.6 on 2021-12-03 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20211203_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
