# Generated by Django 3.1.6 on 2021-12-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211205_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='url',
            new_name='posts',
        ),
        migrations.AddField(
            model_name='node',
            name='users',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
