# Generated by Django 3.1.6 on 2021-10-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211026_0128'),
        ('posts', '0004_auto_20211026_1108'),
    ]

    operations = [
    ]
