# Generated by Django 3.1.6 on 2021-12-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211206_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='posts',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='node',
            name='users',
        ),
    ]
