# Generated by Django 3.2.8 on 2021-11-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_unlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.IntegerField(choices=[(0, 'text/plain'), (1, 'text/markdown')], default='text/plain'),
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'PUBLIC'), (1, 'PRIVATE'), (2, 'FRIENDS')], default=0),
        ),
    ]
