# Generated by Django 3.2.8 on 2021-10-29 04:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 4, 24, 4, 256834, tzinfo=utc)),
        ),
    ]
