# Generated by Django 3.2.8 on 2021-10-29 04:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 4, 26, 51, 189403, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 4, 26, 51, 188404, tzinfo=utc)),
        ),
    ]
