# Generated by Django 3.1.6 on 2021-11-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20211123_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.IntegerField(choices=[(0, 'text/plain'), (1, 'text/markdown')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
