# Generated by Django 3.1.6 on 2021-11-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211126_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_on',
        ),
    ]
