# Generated by Django 3.1.6 on 2021-11-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211126_1243'),
        ('posts', '0011_post_shared_on'),
    ]

    operations = [
    ]
