# Generated by Django 3.2.9 on 2021-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_merge_20211126_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
