# Generated by Django 3.1.6 on 2021-12-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
