# Generated by Django 3.2.9 on 2021-12-04 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_post_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share',
            field=models.ManyToManyField(related_name='posts_shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
