# Generated by Django 3.1.6 on 2021-12-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20211204_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
    ]
