# Generated by Django 3.2.9 on 2021-12-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_link',
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.IntegerField(choices=[(0, 'text/plain'), (1, 'text/markdown'), (2, 'image')], default=0),
        ),
    ]
